// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/domsu/stranger-chat/handler (interfaces: IAppRequestHandler)

// Package mocks is a generated GoMock package.
package mocks

import (
	googleactions "github.com/domsu/stranger-chat/model/external/googleactions"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockIAppRequestHandler is a mock of IAppRequestHandler interface
type MockIAppRequestHandler struct {
	ctrl     *gomock.Controller
	recorder *MockIAppRequestHandlerMockRecorder
}

// MockIAppRequestHandlerMockRecorder is the mock recorder for MockIAppRequestHandler
type MockIAppRequestHandlerMockRecorder struct {
	mock *MockIAppRequestHandler
}

// NewMockIAppRequestHandler creates a new mock instance
func NewMockIAppRequestHandler(ctrl *gomock.Controller) *MockIAppRequestHandler {
	mock := &MockIAppRequestHandler{ctrl: ctrl}
	mock.recorder = &MockIAppRequestHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIAppRequestHandler) EXPECT() *MockIAppRequestHandlerMockRecorder {
	return m.recorder
}

// HandleRequest mocks base method
func (m *MockIAppRequestHandler) HandleRequest(arg0 googleactions.AppRequest) googleactions.Response {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleRequest", arg0)
	ret0, _ := ret[0].(googleactions.Response)
	return ret0
}

// HandleRequest indicates an expected call of HandleRequest
func (mr *MockIAppRequestHandlerMockRecorder) HandleRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleRequest", reflect.TypeOf((*MockIAppRequestHandler)(nil).HandleRequest), arg0)
}
