// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/domsu/stranger-chat/handler (interfaces: IStatsRequestHandler)

// Package mocks is a generated GoMock package.
package mocks

import (
	model "github.com/domsu/stranger-chat/model"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockIStatsRequestHandler is a mock of IStatsRequestHandler interface
type MockIStatsRequestHandler struct {
	ctrl     *gomock.Controller
	recorder *MockIStatsRequestHandlerMockRecorder
}

// MockIStatsRequestHandlerMockRecorder is the mock recorder for MockIStatsRequestHandler
type MockIStatsRequestHandlerMockRecorder struct {
	mock *MockIStatsRequestHandler
}

// NewMockIStatsRequestHandler creates a new mock instance
func NewMockIStatsRequestHandler(ctrl *gomock.Controller) *MockIStatsRequestHandler {
	mock := &MockIStatsRequestHandler{ctrl: ctrl}
	mock.recorder = &MockIStatsRequestHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIStatsRequestHandler) EXPECT() *MockIStatsRequestHandlerMockRecorder {
	return m.recorder
}

// HandleRequest mocks base method
func (m *MockIStatsRequestHandler) HandleRequest() model.StatsResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleRequest")
	ret0, _ := ret[0].(model.StatsResponse)
	return ret0
}

// HandleRequest indicates an expected call of HandleRequest
func (mr *MockIStatsRequestHandlerMockRecorder) HandleRequest() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleRequest", reflect.TypeOf((*MockIStatsRequestHandler)(nil).HandleRequest))
}
