// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/domsu/stranger-chat/model/transformer (interfaces: IPartialRequestTransformer)

// Package mocks is a generated GoMock package.
package mocks

import (
	model "github.com/domsu/stranger-chat/model"
	googleactions "github.com/domsu/stranger-chat/model/external/googleactions"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockIPartialRequestTransformer is a mock of IPartialRequestTransformer interface
type MockIPartialRequestTransformer struct {
	ctrl     *gomock.Controller
	recorder *MockIPartialRequestTransformerMockRecorder
}

// MockIPartialRequestTransformerMockRecorder is the mock recorder for MockIPartialRequestTransformer
type MockIPartialRequestTransformerMockRecorder struct {
	mock *MockIPartialRequestTransformer
}

// NewMockIPartialRequestTransformer creates a new mock instance
func NewMockIPartialRequestTransformer(ctrl *gomock.Controller) *MockIPartialRequestTransformer {
	mock := &MockIPartialRequestTransformer{ctrl: ctrl}
	mock.recorder = &MockIPartialRequestTransformerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIPartialRequestTransformer) EXPECT() *MockIPartialRequestTransformerMockRecorder {
	return m.recorder
}

// Transform mocks base method
func (m *MockIPartialRequestTransformer) Transform(arg0 googleactions.AppRequest) model.PartialRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Transform", arg0)
	ret0, _ := ret[0].(model.PartialRequest)
	return ret0
}

// Transform indicates an expected call of Transform
func (mr *MockIPartialRequestTransformerMockRecorder) Transform(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transform", reflect.TypeOf((*MockIPartialRequestTransformer)(nil).Transform), arg0)
}
